### ISSUE TITLE
Minimum Python version?

### ISSUE THREAD

**Issue by alanhogan** [Leftium/mailsnake#3]
Is this compatible with Python 2.4? Is there a known minimum Python version requirement?

**Comment by alanhogan** [comment]
I’m on MediaTemple and getting an error: `ImportError: No module named json`.

The fix was an `import simplejson as json` (after installing simplejson).

**Comment by Leftium** [comment]
Addressed by [this commit and comment](https://github.com/leftium/mailsnake/pull/5#issuecomment-1412094).
