### ISSUE TITLE
Upload mailsnake to PyPi packages

### ISSUE THREAD

**Issue by maraujop** [Leftium/mailsnake#7]
Hi there,

I think having mailsnake in PyPi would be a great thing, that simplifies deployment and requirements automation when using it, so we can do:

``` sh
pip install mailsnake
```

BTW very well done tiny wrapper API, beautiful! Cheers
Miguel

**Comment by mihow** [comment]
Agreed! The setup.py already says:

`download_url = "http://pypi.python.org/pypi/mailsnake/"`

But that page doesn't exist :(

**Comment by camilonova** [comment]
+1

**Comment by AdrianRibao** [comment]
+1

**Comment by michaelhelmick** [comment]
+1

**Comment by camilonova** [comment]
Is now here:

http://pypi.python.org/pypi/mailsnake

You can close this issue now

**Comment by michaelhelmick** [comment]
@camilonova Just in case you didn't see, I'm now maintaining this repository at https://github.com/michaelhelmick/python-mailsnake

**Comment by camilonova** [comment]
@michaelhelmick great to know, im going to your side
